/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fi.soveltia.arquillian.servicebuilder.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GuestbookEntry service. Represents a row in the &quot;svc_test_GuestbookEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.soveltia.arquillian.servicebuilder.model.impl.GuestbookEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.soveltia.arquillian.servicebuilder.model.impl.GuestbookEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GuestbookEntry
 * @see fi.soveltia.arquillian.servicebuilder.model.impl.GuestbookEntryImpl
 * @see fi.soveltia.arquillian.servicebuilder.model.impl.GuestbookEntryModelImpl
 * @generated
 */
@ProviderType
public interface GuestbookEntryModel extends BaseModel<GuestbookEntry>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a guestbook entry model instance should use the {@link GuestbookEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this guestbook entry.
	 *
	 * @return the primary key of this guestbook entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this guestbook entry.
	 *
	 * @param primaryKey the primary key of this guestbook entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this guestbook entry.
	 *
	 * @return the uuid of this guestbook entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this guestbook entry.
	 *
	 * @param uuid the uuid of this guestbook entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this guestbook entry.
	 *
	 * @return the entry ID of this guestbook entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this guestbook entry.
	 *
	 * @param entryId the entry ID of this guestbook entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this guestbook entry.
	 *
	 * @return the group ID of this guestbook entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this guestbook entry.
	 *
	 * @param groupId the group ID of this guestbook entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this guestbook entry.
	 *
	 * @return the company ID of this guestbook entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this guestbook entry.
	 *
	 * @param companyId the company ID of this guestbook entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this guestbook entry.
	 *
	 * @return the user ID of this guestbook entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this guestbook entry.
	 *
	 * @param userId the user ID of this guestbook entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this guestbook entry.
	 *
	 * @return the user uuid of this guestbook entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this guestbook entry.
	 *
	 * @param userUuid the user uuid of this guestbook entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this guestbook entry.
	 *
	 * @return the create date of this guestbook entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this guestbook entry.
	 *
	 * @param createDate the create date of this guestbook entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the text of this guestbook entry.
	 *
	 * @return the text of this guestbook entry
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this guestbook entry.
	 *
	 * @param text the text of this guestbook entry
	 */
	public void setText(String text);

	/**
	 * Returns the author of this guestbook entry.
	 *
	 * @return the author of this guestbook entry
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this guestbook entry.
	 *
	 * @param author the author of this guestbook entry
	 */
	public void setAuthor(String author);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		fi.soveltia.arquillian.servicebuilder.model.GuestbookEntry guestbookEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<fi.soveltia.arquillian.servicebuilder.model.GuestbookEntry> toCacheModel();

	@Override
	public fi.soveltia.arquillian.servicebuilder.model.GuestbookEntry toEscapedModel();

	@Override
	public fi.soveltia.arquillian.servicebuilder.model.GuestbookEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}