/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package fi.soveltia.arquillian.servicebuilder.model.impl;

import aQute.bnd.annotation.ProviderType;

import fi.soveltia.arquillian.servicebuilder.model.GuestbookEntry;
import fi.soveltia.arquillian.servicebuilder.service.GuestbookEntryLocalServiceUtil;

/**
 * The extended model base implementation for the GuestbookEntry service. Represents a row in the &quot;svc_test_GuestbookEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuestbookEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GuestbookEntryImpl
 * @see GuestbookEntry
 * @generated
 */
@ProviderType
public abstract class GuestbookEntryBaseImpl extends GuestbookEntryModelImpl
	implements GuestbookEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a guestbook entry model instance should use the {@link GuestbookEntry} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GuestbookEntryLocalServiceUtil.addGuestbookEntry(this);
		}
		else {
			GuestbookEntryLocalServiceUtil.updateGuestbookEntry(this);
		}
	}
}